### ISSUE TITLE
Fix GunChargBlasterHeavy having no melee damage attributes

### ISSUE THREAD

**Issue by Juanfrank** [Juanfrank/AA_CombatExtendedPatch#10]
`Trying to get stat MeleeDamage from Gun_ChargeBlasterHeavy which has no support for Combat Extended.
Verse.Log:Error(String, Boolean)
CombatExtended.StatWorker_MeleeDamage:GetStatDrawEntryLabel(StatDef, Single, ToStringNumberSense, StatRequest, Boolean)
RimWorld.StatDrawEntry:get_ValueString()
RimWorld.StatDrawEntry:Draw(Single, Single, Single, Boolean, Action, Action, Vector2, Rect)
RimWorld.StatsReportUtility:DrawStatsWorker(Rect, Thing, WorldObject)
RimWorld.StatsReportUtility:DrawStatsReport(Rect, Thing)
Verse.Dialog_InfoCard:FillCard(Rect)
Verse.Dialog_InfoCard:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
`

**Comment by Breadbox2k19** [comment]
Heavy charge blaster is a vanilla weapon, I guess it was never patched with a CE compatible melee attack, this fix should be proposed to the CE github itself.

**Comment by Juanfrank** [comment]
Pull request done to main CE repository in https://github.com/CombatExtended-Continued/CombatExtended/pull/14. I'll mark this as closed since it'll fix itself when the PR is accepted.
