### ISSUE TITLE
Fix the DamageWorkers

### ISSUE THREAD

**Issue by Juanfrank** [Juanfrank/AA_CombatExtendedPatch#102]
Change the corresponding damageworkers to CE's ones, preferably using generic Defs and tons of or's.

**Comment by Juanfrank** [comment]
DamageWorkers used in AA:
- DamageWorker_Stab
- AlphaBehavioursAndEvents.DamageWorker_ExtraInfecter
- AlphaBehavioursAndEvents.DamageWorker_ExtraDamageInsectoids
- DamageWorker_AddInjury
- AlphaBehavioursAndEvents.DamageWorker_Siege
- AlphaBehavioursAndEvents.DamageWorker_Vampiric
- DamageWorker_Blunt

CE:
- CombatExtended.DamageWorker_AddInjuryCE
- CombatExtended.DamageWorker_FlameCE
- Removed vanilla DamageWorkers (Defnames Poke, Stab, Cut, Scratch, and Bite) - Replaced with normal DamageWorker_AddInjury which I believe later one becomes CombatExtended.DamageWorker_AddInjuryCE
- CombatExtended.DamageWorker_BluntCE

Notes harm outside layers
```
<Operation Class="PatchOperationAddModExtension">
  	<xpath>Defs/DamageDef[defName="ScratchToxic"]</xpath>
  	<value>
  		<li Class="CombatExtended.DamageDefExtensionCE">
  			<harmOnlyOutsideLayers>true</harmOnlyOutsideLayers>
  		</li>
  	</value>
	</Operation>

```
Ambient damage
```
      <li Class="CombatExtended.DamageDefExtensionCE">
        <isAmbientDamage>true</isAmbientDamage>
      </li>
```

**Comment by Juanfrank** [comment]
Done in https://github.com/Juanfrank/AA_CombatExtendedPatch/commit/1c6774934d69fa956868b46b953670e6c40e334e

**Comment by Breadbox2k19** [comment]
I would suggest increasing the effect of AA_Toxicsting. AA_Toxic Bolt, very toxic sting damage and any attack that deals toxic or acid buildup hediff. Currently, they have no effect on combat whatsoever.
Due to how CE works, one is likely to bleed to death before toxic buildup ever goes above 5%.

**Comment by Juanfrank** [comment]
Done in https://github.com/Juanfrank/AA_CombatExtendedPatch/commit/1a83aa17bea4a0007aef62b4f7e72eb63fd9ad8f

**Comment by Breadbox2k19** [comment]
Thanks.
I think we are done here and the patch is ready for review.
