### ISSUE TITLE
Verb_Shoot all races with ranged attacks

### ISSUE THREAD

**Issue by Juanfrank** [Juanfrank/AA_CombatExtendedPatch#12]

**Comment by Breadbox2k19** [comment]
I believe accuracy stats need to be added to all the animals using ranged attacks as well.

**Comment by Juanfrank** [comment]
Self-note that the verbProperties was added without any red errors whatsoever. Now Playtesting b4 uploading.

**Comment by Juanfrank** [comment]
Tested. CE VerbProperties seems to be incompatible with gunless ranged attacks. In the meantime, the provided XML doesn't show up any errors on RW opening and loading saves. Issue comes when these creatures attack.

Dragons also seem to have `<!--Commented-->` their similar code, which seems to suggest they tried to use the same method and didn't succeed.

Moved to bugfixing and archived.

**Comment by Juanfrank** [comment]
https://github.com/Juanfrank/AA_CombatExtendedPatch/tree/VerbShootCE

**Comment by Juanfrank** [comment]
Fixed with 8f89e69f01e9d38483a6e24d2105319158cd92c2
