### ISSUE TITLE
Band-aid fixes to animal range attack

### ISSUE THREAD

**Issue by Breadbox2k19** [Juanfrank/AA_CombatExtendedPatch#27]
To make animal range attack more useable, I'm thinking that some of animal attacks could be made into a 1 tile aoe attack like webs and plasma attack.

The problem is how to make the aoe attack not have the explosion visual effect.

**Comment by Juanfrank** [comment]
Are you having the same issue where animals are having shit accuracy and won't hit the side of a barn?

**Comment by Breadbox2k19** [comment]
Of course I have the same issue, I'm have tried patching the animal ranged attack months ago, with similar results.

**Comment by Juanfrank** [comment]
Does setting their shootingaccuracy help at all?

**Comment by Breadbox2k19** [comment]
Not really no, I'll try setting a very high number later.

**Comment by Juanfrank** [comment]
Fixed with 8f89e69f01e9d38483a6e24d2105319158cd92c2
