### ISSUE TITLE
Sand cloak not working

### ISSUE THREAD

**Issue by Juanfrank** [Juanfrank/AA_CombatExtendedPatch#44]
I'll try changing the rate and radius values from the RaceDef to make the smoke not be as easily avoided as right now (the rate and radius is so low it actually makes it easy to hit him when he's rushing at someone).

_Originally posted by @Juanfrank in https://github.com/Juanfrank/AA_CombatExtendedPatch/pull/36#issuecomment-617573446_

**Comment by Juanfrank** [comment]
@Breadbox2k19 are there any other creatures that produce a similar effect?

**Comment by Breadbox2k19** [comment]
> @Breadbox2k19 are there any other creatures that produce a similar effect?

There are a few animals that produces obvious smoke, like the ocular jelly. The others are really hard to notice.
